rvm: 2.0.0
sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
before_script:
  - npm install benderjs-cli --save-dev
  - npm install -g bender-cli
  - npm install -g phantomjs
  - bender init
